name: Highball
options:
  bundleIdPrefix: com.highball
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"

packages:
  KeychainAccess:
    url: https://github.com/kishikawakatsumi/KeychainAccess
    version: 4.2.2

targets:
  Highball:
    type: application
    platform: macOS
    sources:
      - Highball
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.highball.app
        PRODUCT_NAME: Highball
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_FILE: Highball/Info.plist
        CODE_SIGN_ENTITLEMENTS: Highball/Highball.entitlements
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_STYLE: Automatic
        SWIFT_VERSION: "5.9"
        GENERATE_INFOPLIST_FILE: NO
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - package: KeychainAccess
    entitlements:
      path: Highball/Highball.entitlements
    info:
      path: Highball/Info.plist
